[package]
name = "micrefektuh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.1.1"
console = "0.15.5"
cpal = "0.14.2"
ctrlc = "3.2.4"
ringbuf = "0.3.2"
